plugins {
    id 'java'
    id 'maven-publish' // 1. 必须引入 maven-publish 插件
}

group 'com.github.yaobin-kid.ultrabar-plugin-sdk'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar() // 推荐：同时打包源码，方便三方开发者看源码和提示
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'io.netty:netty-all:4.1.94.Final'
  implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
  implementation 'org.slf4j:slf4j-simple:2.0.7'
  testImplementation 'junit:junit:4.13.2'
}

compileJava {
    options.encoding = 'UTF-8'
}



// 3. 配置 maven 发布规则，让 JitPack 知道要发布什么
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}
